import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  applyCommand,
  createGame,
  hydrateGame,
  RESULT_ELIGIBILITY_POLICY,
  type GameCommand,
  type GameResult,
  type GameState,
  type PhysicalTile,
} from "../src/domain/game";
import { competitiveResultEligible } from "../src/domain/records";
import type { Letter, Lexicon, Placement } from "../src/domain/types";

// Journals generated by parent commit 23c532b (before verified additions became
// eligible). They must load unchanged; never regenerate them with current code.
const fixture = JSON.parse(
  readFileSync(
    new URL("./fixtures/legacy-finalized-games.json", import.meta.url),
    "utf8",
  ),
) as { generatedBy: string; games: Record<string, GameState> };
const lexicon: Lexicon = {
  id: "legacy-fixture",
  edition: "1",
  status: "ready",
  has: (word) => ["CAT", "CATS", "READING"].includes(word),
};
const legacy = (name: string) =>
  structuredClone(fixture.games[name]) as GameState & Record<string, unknown>;
const load = (value: unknown) => hydrateGame(value, lexicon);
const rejected = (result: GameResult) => {
  expect(result.ok).toBe(false);
  if (!result.ok) expect(result.error.code).toBe("INVALID_SAVED_GAME");
};
const finalEvent = (game: GameState) => game.events.at(-1)!;

const seven = (text: string) => text.split("") as PhysicalTile[];
const place = (word: string): Placement[] =>
  [...word].map((letter, i) => ({
    row: 7,
    col: 7 + i,
    tile: { letter: letter as Letter, blank: false },
  }));
const dog = {
  word: "DOG",
  source: "merriam-webster" as const,
  sourceUrl: "https://scrabble.merriam.com/finder/dog",
  verifiedAt: "2026-09-20T17:00:00.000Z",
};
function play(options: {
  verify?: boolean;
  word?: string;
  extendSupply?: boolean;
  ending?: "blocked" | "early";
}): GameState {
  const ok = (r: GameResult) => {
    if (!r.ok) throw new Error(`${r.error.code}: ${r.error.message}`);
    return r.game;
  };
  let g = ok(
    createGame({
      id: "current",
      players: [
        { id: "a", name: "Doug", seat: 0 },
        { id: "b", name: "Emma", seat: 2 },
      ],
      firstPlayerId: "a",
      direction: "clockwise",
      lexicon: { id: lexicon.id, edition: lexicon.edition, status: "ready" },
      createdAt: "2026-09-28T20:00:00.000Z",
    }),
  );
  const cmd = (payload: Record<string, unknown>) =>
    (g = ok(
      applyCommand(
        g,
        {
          id: `c-${g.revision + 1}`,
          expectedRevision: g.revision,
          ...payload,
        } as GameCommand,
        lexicon,
      ),
    ));
  if (options.verify) cmd({ type: "verify-words", words: [dog] });
  if (options.extendSupply)
    cmd({
      type: "extend-supply",
      additions: { Q: 1 },
      reason: "The physical set includes an additional Q",
      recordedBy: "Doug",
      recordedAt: "2026-09-28T12:00:00.000Z",
    });
  cmd({ type: "play", placements: place(options.word ?? "CAT") });
  if (options.ending !== "early")
    for (let i = 0; i < 4; i++) cmd({ type: "pass" });
  cmd({
    type: "finalize",
    reason: options.ending ?? "blocked",
    racks: { a: seven("AAAAIII"), b: seven("EEEEERT") },
  });
  return g;
}

describe("journals finalized before the result eligibility policy", () => {
  it("comes from the parent commit and records the original eligibility", () => {
    expect(fixture.generatedBy).toBe("23c532b");
    for (const name of ["playedAddition", "unplayedAddition", "noAddition"])
      expect(Object.hasOwn(legacy(name).result!, "eligibilityPolicy")).toBe(
        false,
      );
    expect(legacy("playedAddition").result!.competitiveEligible).toBe(false);
    expect(legacy("unplayedAddition").result!.competitiveEligible).toBe(false);
    expect(legacy("noAddition").result!.competitiveEligible).toBe(true);
  });
  it("loads every legacy journal without rewriting recorded events or results", () => {
    for (const name of ["playedAddition", "unplayedAddition", "noAddition"]) {
      const saved = legacy(name);
      const loaded = load(structuredClone(saved));
      expect(loaded.ok).toBe(true);
      if (!loaded.ok) continue;
      expect(JSON.parse(JSON.stringify(loaded.game))).toEqual(saved);
      expect(loaded.game.events).toEqual(saved.events);
      expect(loaded.game.result).toEqual(saved.result);
    }
  });
  it("keeps the recorded rules in domain records", () => {
    expect(competitiveResultEligible(legacy("playedAddition"))).toBe(false);
    expect(competitiveResultEligible(legacy("unplayedAddition"))).toBe(false);
    expect(competitiveResultEligible(legacy("noAddition"))).toBe(true);
  });
  it("still rejects tampered scores, winners, adjustments and eligibility", () => {
    const edits: ((g: GameState) => void)[] = [
      (g) => (finalEvent(g).result!.scores.a += 1),
      (g) => (finalEvent(g).result!.winnerIds = ["a", "b"]),
      (g) => (finalEvent(g).result!.adjustments.b.deduction = 0),
      (g) => (finalEvent(g).result!.competitiveEligible = true),
      (g) => (finalEvent(g).result!.actualBagCount += 1),
      (g) => (g.result!.scores.b -= 1),
      (g) => (g.result!.competitiveEligible = true),
    ];
    for (const edit of edits) {
      const saved = legacy("playedAddition");
      edit(saved);
      rejected(load(saved));
    }
  });
  it("still rejects tampered unrelated event fields", () => {
    const edits: ((g: GameState) => void)[] = [
      (g) => (g.events[1].turn!.score += 1),
      (g) => (g.events[0].fingerprint = "{}"),
      (g) =>
        ((g.events.at(-1)!.command as { reason: string }).reason = "early"),
      (g) => (g.events.at(-1)!.sequence += 1),
      (g) => g.events.splice(0, 1),
    ];
    for (const edit of edits) {
      const saved = legacy("playedAddition");
      edit(saved);
      rejected(load(saved));
    }
  });
  it("cannot be upgraded to the current policy by adding its marker alone", () => {
    const saved = legacy("playedAddition");
    finalEvent(saved).result!.eligibilityPolicy = RESULT_ELIGIBILITY_POLICY;
    saved.result!.eligibilityPolicy = RESULT_ELIGIBILITY_POLICY;
    rejected(load(saved));
  });
});

describe("results finalized under the current policy", () => {
  it("stay eligible with a played or unplayed verified addition and replay exactly", () => {
    for (const word of ["DOG", "CAT"]) {
      const game = play({ verify: true, word });
      expect(game.result!.eligibilityPolicy).toBe(RESULT_ELIGIBILITY_POLICY);
      expect(game.result!.competitiveEligible).toBe(true);
      expect(competitiveResultEligible(game)).toBe(true);
      const loaded = load(JSON.parse(JSON.stringify(game)));
      expect(loaded.ok && loaded.game).toEqual(game);
    }
  });
  it("reject a removed or altered policy marker", () => {
    for (const value of [undefined, 1, 3, "2"]) {
      const saved = JSON.parse(
        JSON.stringify(play({ verify: true, word: "DOG" })),
      );
      for (const result of [finalEvent(saved).result, saved.result])
        if (value === undefined) delete result.eligibilityPolicy;
        else result.eligibilityPolicy = value;
      rejected(load(saved));
    }
  });
  it("keep custom-supply and early-ending exclusions when additions exist", () => {
    for (const game of [
      play({ verify: true, word: "DOG", extendSupply: true }),
      play({ verify: true, word: "DOG", ending: "early" }),
    ]) {
      expect(game.result!.competitiveEligible).toBe(false);
      expect(competitiveResultEligible(game)).toBe(false);
      const loaded = load(JSON.parse(JSON.stringify(game)));
      expect(loaded.ok && loaded.game).toEqual(game);
    }
  });
});
